// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package spi_subsystem_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } use_axi;
    struct packed {
      logic        q;
    } a2f_ctr_poweron_en;
    struct packed {
      logic        q;
    } a2f_ctr_quadspi_en;
  } spi_subsystem_reg2hw_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } use_axi;
    struct packed {
      logic        d;
      logic        de;
    } a2f_ctr_poweron_en;
    struct packed {
      logic        d;
      logic        de;
    } a2f_ctr_quadspi_en;
  } spi_subsystem_hw2reg_control_reg_t;

  // Register -> HW type
  typedef struct packed {
    spi_subsystem_reg2hw_control_reg_t control; // [2:0]
  } spi_subsystem_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    spi_subsystem_hw2reg_control_reg_t control; // [5:0]
  } spi_subsystem_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SPI_SUBSYSTEM_CONTROL_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    SPI_SUBSYSTEM_CONTROL
  } spi_subsystem_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SPI_SUBSYSTEM_PERMIT [1] = '{
    4'b 0001  // index[0] SPI_SUBSYSTEM_CONTROL
  };

endpackage

