// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module spi_subsystem_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 2
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output spi_subsystem_reg_pkg::spi_subsystem_reg2hw_t reg2hw, // Write
  input  spi_subsystem_reg_pkg::spi_subsystem_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import spi_subsystem_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic control_use_axi_qs;
  logic control_use_axi_wd;
  logic control_use_axi_we;
  logic control_a2f_ctr_poweron_en_qs;
  logic control_a2f_ctr_poweron_en_wd;
  logic control_a2f_ctr_poweron_en_we;
  logic control_a2f_ctr_quadspi_en_qs;
  logic control_a2f_ctr_quadspi_en_wd;
  logic control_a2f_ctr_quadspi_en_we;

  // Register instances
  // R[control]: V(False)

  //   F[use_axi]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_control_use_axi (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_use_axi_we),
    .wd     (control_use_axi_wd),

    // from internal hardware
    .de     (hw2reg.control.use_axi.de),
    .d      (hw2reg.control.use_axi.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.use_axi.q ),

    // to register interface (read)
    .qs     (control_use_axi_qs)
  );


  //   F[a2f_ctr_poweron_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_control_a2f_ctr_poweron_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_a2f_ctr_poweron_en_we),
    .wd     (control_a2f_ctr_poweron_en_wd),

    // from internal hardware
    .de     (hw2reg.control.a2f_ctr_poweron_en.de),
    .d      (hw2reg.control.a2f_ctr_poweron_en.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.a2f_ctr_poweron_en.q ),

    // to register interface (read)
    .qs     (control_a2f_ctr_poweron_en_qs)
  );


  //   F[a2f_ctr_quadspi_en]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_control_a2f_ctr_quadspi_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (control_a2f_ctr_quadspi_en_we),
    .wd     (control_a2f_ctr_quadspi_en_wd),

    // from internal hardware
    .de     (hw2reg.control.a2f_ctr_quadspi_en.de),
    .d      (hw2reg.control.a2f_ctr_quadspi_en.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.control.a2f_ctr_quadspi_en.q ),

    // to register interface (read)
    .qs     (control_a2f_ctr_quadspi_en_qs)
  );




  logic [0:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == SPI_SUBSYSTEM_CONTROL_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(SPI_SUBSYSTEM_PERMIT[0] & ~reg_be)))));
  end

  assign control_use_axi_we = addr_hit[0] & reg_we & !reg_error;
  assign control_use_axi_wd = reg_wdata[0];

  assign control_a2f_ctr_poweron_en_we = addr_hit[0] & reg_we & !reg_error;
  assign control_a2f_ctr_poweron_en_wd = reg_wdata[1];

  assign control_a2f_ctr_quadspi_en_we = addr_hit[0] & reg_we & !reg_error;
  assign control_a2f_ctr_quadspi_en_wd = reg_wdata[2];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = control_use_axi_qs;
        reg_rdata_next[1] = control_a2f_ctr_poweron_en_qs;
        reg_rdata_next[2] = control_a2f_ctr_quadspi_en_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module spi_subsystem_reg_top_intf
#(
  parameter int AW = 2,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output spi_subsystem_reg_pkg::spi_subsystem_reg2hw_t reg2hw, // Write
  input  spi_subsystem_reg_pkg::spi_subsystem_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  spi_subsystem_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


