// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module w25q128jw_controller_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 6
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output w25q128jw_controller_reg_pkg::w25q128jw_controller_reg2hw_t reg2hw,  // Write
    input w25q128jw_controller_reg_pkg::w25q128jw_controller_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import w25q128jw_controller_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic control_start_qs;
  logic control_start_wd;
  logic control_start_we;
  logic control_rnw_qs;
  logic control_rnw_wd;
  logic control_rnw_we;
  logic status_qs;
  logic status_wd;
  logic status_we;
  logic [31:0] f_address_qs;
  logic [31:0] f_address_wd;
  logic f_address_we;
  logic [31:0] s_address_qs;
  logic [31:0] s_address_wd;
  logic s_address_we;
  logic [31:0] md_address_qs;
  logic [31:0] md_address_wd;
  logic md_address_we;
  logic [31:0] length_qs;
  logic [31:0] length_wd;
  logic length_we;
  logic intr_status_qs;
  logic intr_status_wd;
  logic intr_status_we;
  logic intr_enable_qs;
  logic intr_enable_wd;
  logic intr_enable_we;
  logic [7:0] dma_slot_wait_counter_qs;
  logic [7:0] dma_slot_wait_counter_wd;
  logic dma_slot_wait_counter_we;

  // Register instances
  // R[control]: V(False)

  //   F[start]: 0:0
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control_start (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_start_we),
      .wd(control_start_wd),

      // from internal hardware
      .de(hw2reg.control.start.de),
      .d (hw2reg.control.start.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.control.start.q),

      // to register interface (read)
      .qs(control_start_qs)
  );


  //   F[rnw]: 1:1
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_control_rnw (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(control_rnw_we),
      .wd(control_rnw_wd),

      // from internal hardware
      .de(hw2reg.control.rnw.de),
      .d (hw2reg.control.rnw.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.control.rnw.q),

      // to register interface (read)
      .qs(control_rnw_qs)
  );


  // R[status]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(status_we),
      .wd(status_wd),

      // from internal hardware
      .de(hw2reg.status.de),
      .d (hw2reg.status.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.status.q),

      // to register interface (read)
      .qs(status_qs)
  );


  // R[f_address]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_f_address (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(f_address_we),
      .wd(f_address_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.f_address.q),

      // to register interface (read)
      .qs(f_address_qs)
  );


  // R[s_address]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_s_address (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(s_address_we),
      .wd(s_address_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.s_address.q),

      // to register interface (read)
      .qs(s_address_qs)
  );


  // R[md_address]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_md_address (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(md_address_we),
      .wd(md_address_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.md_address.q),

      // to register interface (read)
      .qs(md_address_qs)
  );


  // R[length]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
  ) u_length (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(length_we),
      .wd(length_wd),

      // from internal hardware
      .de(hw2reg.length.de),
      .d (hw2reg.length.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.length.q),

      // to register interface (read)
      .qs(length_qs)
  );


  // R[intr_status]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_intr_status (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(intr_status_we),
      .wd(intr_status_wd),

      // from internal hardware
      .de(hw2reg.intr_status.de),
      .d (hw2reg.intr_status.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.intr_status.q),

      // to register interface (read)
      .qs(intr_status_qs)
  );


  // R[intr_enable]: V(False)

  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_intr_enable (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(intr_enable_we),
      .wd(intr_enable_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.intr_enable.q),

      // to register interface (read)
      .qs(intr_enable_qs)
  );


  // R[dma_slot_wait_counter]: V(False)

  prim_subreg #(
      .DW      (8),
      .SWACCESS("RW"),
      .RESVAL  (8'h0)
  ) u_dma_slot_wait_counter (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(dma_slot_wait_counter_we),
      .wd(dma_slot_wait_counter_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.dma_slot_wait_counter.q),

      // to register interface (read)
      .qs(dma_slot_wait_counter_qs)
  );




  logic [8:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == W25Q128JW_CONTROLLER_CONTROL_OFFSET);
    addr_hit[1] = (reg_addr == W25Q128JW_CONTROLLER_STATUS_OFFSET);
    addr_hit[2] = (reg_addr == W25Q128JW_CONTROLLER_F_ADDRESS_OFFSET);
    addr_hit[3] = (reg_addr == W25Q128JW_CONTROLLER_S_ADDRESS_OFFSET);
    addr_hit[4] = (reg_addr == W25Q128JW_CONTROLLER_MD_ADDRESS_OFFSET);
    addr_hit[5] = (reg_addr == W25Q128JW_CONTROLLER_LENGTH_OFFSET);
    addr_hit[6] = (reg_addr == W25Q128JW_CONTROLLER_INTR_STATUS_OFFSET);
    addr_hit[7] = (reg_addr == W25Q128JW_CONTROLLER_INTR_ENABLE_OFFSET);
    addr_hit[8] = (reg_addr == W25Q128JW_CONTROLLER_DMA_SLOT_WAIT_COUNTER_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(W25Q128JW_CONTROLLER_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(W25Q128JW_CONTROLLER_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(W25Q128JW_CONTROLLER_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(W25Q128JW_CONTROLLER_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(W25Q128JW_CONTROLLER_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(W25Q128JW_CONTROLLER_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(W25Q128JW_CONTROLLER_PERMIT[6] & ~reg_be))) |
               (addr_hit[7] & (|(W25Q128JW_CONTROLLER_PERMIT[7] & ~reg_be))) |
               (addr_hit[8] & (|(W25Q128JW_CONTROLLER_PERMIT[8] & ~reg_be)))));
  end

  assign control_start_we = addr_hit[0] & reg_we & !reg_error;
  assign control_start_wd = reg_wdata[0];

  assign control_rnw_we = addr_hit[0] & reg_we & !reg_error;
  assign control_rnw_wd = reg_wdata[1];

  assign status_we = addr_hit[1] & reg_we & !reg_error;
  assign status_wd = reg_wdata[0];

  assign f_address_we = addr_hit[2] & reg_we & !reg_error;
  assign f_address_wd = reg_wdata[31:0];

  assign s_address_we = addr_hit[3] & reg_we & !reg_error;
  assign s_address_wd = reg_wdata[31:0];

  assign md_address_we = addr_hit[4] & reg_we & !reg_error;
  assign md_address_wd = reg_wdata[31:0];

  assign length_we = addr_hit[5] & reg_we & !reg_error;
  assign length_wd = reg_wdata[31:0];

  assign intr_status_we = addr_hit[6] & reg_we & !reg_error;
  assign intr_status_wd = reg_wdata[0];

  assign intr_enable_we = addr_hit[7] & reg_we & !reg_error;
  assign intr_enable_wd = reg_wdata[0];

  assign dma_slot_wait_counter_we = addr_hit[8] & reg_we & !reg_error;
  assign dma_slot_wait_counter_wd = reg_wdata[7:0];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = control_start_qs;
        reg_rdata_next[1] = control_rnw_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = status_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = f_address_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = s_address_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = md_address_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = length_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[0] = intr_status_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[0] = intr_enable_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[7:0] = dma_slot_wait_counter_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module w25q128jw_controller_reg_top_intf #(
    parameter  int AW = 6,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output w25q128jw_controller_reg_pkg::w25q128jw_controller_reg2hw_t reg2hw,  // Write
    input w25q128jw_controller_reg_pkg::w25q128jw_controller_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  w25q128jw_controller_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


